### ISSUE TITLE
Include a link to what Procfile.dev actually is

### ISSUE THREAD

**Issue by Maia-Everett** [albarrync/procfile#1]
People are likely to find your site by searching for what a Procfile.dev actually is (as did I), so it might be helpful to include a link to an external page explaining that!

**Comment by albarrync** [comment]
> People are likely to find your site by searching for what a Procfile.dev actually is (as did I), so it might be helpful to include a link to an external page explaining that!

This is a great idea @Maia-Everett 
I'll get some better info up ASAP. Much appreciated!

**Comment by albarrync** [comment]
Thank you @Maia-Everett !
I need to clean up formatting in a few places, but #2 should get some better information to folks in the short term.

**Comment by Maia-Everett** [comment]
Looks good, thanks. Closing the issue!
